env:
    browser: true
    es2021: true
extends:
    - standard-with-typescript
    - plugin:react/recommended
    # - plugin:react/jsx-runtime
    - prettier
parserOptions:
    ecmaVersion: latest
    sourceType: module
    project: ['tsconfig.json']
plugins:
    - react
globals: { __IS_DEV__: true }
rules: {
        # 'indent': ['error', 4],
        # 'react/jsx-indent': [2, 4],
        # 'react/jsx-indent-props': [2, 4],
        # # // "indent": ["error", 4],
        # #   // 'react/jsx-indent': [2, 2],
        # #   // 'react/jsx-indent': [2, 2, { ignoreTernaryOperators: true }],
        'react/jsx-filename-extension':
            [2, { extensions: ['.js', '.jsx', '.tsx'] }],
        'import/no-unresolved': 'off',
        'import/prefer-default-export': 'off',
        'no-unused-vars': 'warn',
        'react/require-default-props': 'off',
        'react/react-in-jsx-scope': 'off',
        'react/jsx-props-no-spreading': 'warn',
        'react/function-component-definition': 'off',
        'no-shadow': 'off',
        'import/extetsions': 'off',
        'import/no-extraneous-dependencies': 'warn',
        'no-underscope-dangle': 'off',
        '@typescript-eslint/strict-boolean-expressions': 'error',
        '@typescript-eslint/prefer-nullish-coalescing': 'error',
    }

